QUESTIONS = [
    ("All plants need soil to grow.", False),
    ("Flowers are the reproductive organs of most plants.", True),
    ("Plants make their own food through photosynthesis using sunlight, water, and carbon dioxide.", True),
    ("Sunflowers can produce energy for other plants around them.", False),
    ("Rainforests have the largest variety of plant species on Earth.", True),
    ("All flowers bloom in spring.", False),
    ("Banana plants are actually giant herbs, not trees.", True),
    ("In Plants vs. Zombies, the Peashooter is based on a real pea plant.", True),
    ("Carnivorous plants like the man-eating plant really exist on Earth.", False),
    ("Cherry Bombs are based on a real plant that can explode.", False),
    ("Carnivorous plants live in nutrient-rich soils.", False),
    ("There is a real plant called the Snow Pea.", True),
    ("Sunflowers always follow the sun, even after they bloom.", False),
    ("Some flowers open only at night.", True),
    ("Apples float in water because they are 25 percent air.", True),
    ("Broccoli is actually a flower.", True),
    ("Carrots used to be purple before they became orange.", True),
    ("Tomatoes are fruits, not vegetables.", True),
    ("The smell of freshly cut grass is actually a distress signal from the plant.", True),
    ("Plants have both male and female parts in the same flower.", True),
    ("There is a plant that can walk by growing new roots and moving slowly across the ground.", True),
    ("The Ice-shroom from the game is based on a real plant that survives freezing by making antifreeze proteins.", True),
    ("Some flowers can actually produce heat to attract insects.", True),
    ("There are real plants that can shoot seeds several meters away.", True),
    ("Coral reefs are made by plants.", False),
]
